// src/components/Layout.vue
<template>
  <div class="shop">
    <div class="cart-bar">
      <div>
        <p class="eyebrow">Your bag</p>
        <p>{{ cartCount ? `${cartCount} item${cartCount > 1 ? 's' : ''}` : 'No items yet' }}</p>
      </div>
      <div style="display: flex; align-items: center; gap: 1rem">
        <template v-if="isAuthenticated">
          <router-link
            to="/account/orders"
            style="color: inherit; text-decoration: none; font-size: 0.875rem; margin-right: 0.5rem"
          >
            {{ user?.email }}
          </router-link>
          <button
            type="button"
            class="btn btn--ghost btn--small"
            style="font-size: 0.875rem"
            @click="logout"
          >
            Logout
          </button>
        </template>
        <template v-else>
          <router-link
            to="/login"
            style="color: inherit; text-decoration: none; font-size: 0.875rem; margin-right: 0.5rem"
          >
            Login
          </router-link>
        </template>
        <button type="button" class="cart-toggle" data-testid="cart-toggle" @click="toggleCart">
          Bag
          <span class="cart-pill" data-testid="cart-count" aria-live="polite">
            {{ cartCount }}
          </span>
        </button>
      </div>
    </div>

    <section v-if="isCartOpen" class="cart-panel cart-panel--open" aria-live="polite">
      <header class="cart-panel__header">
        <div>
          <p class="eyebrow">Shopping bag</p>
          <h2>Ready to ship</h2>
        </div>
        <button type="button" class="btn btn--ghost btn--small" @click="toggleCart">Hide</button>
      </header>
      <p class="cart-panel__note">{{ freeShippingMessage }}</p>
      <ul v-if="cartItems.length > 0" class="cart-panel__lines">
        <li v-for="item in cartItems" :key="item.product.id" class="cart-line">
          <div class="cart-line__info">
            <p>{{ item.product.name }}</p>
            <span>{{ currency.format(item.product.price) }}</span>
          </div>
          <div class="cart-line__controls">
            <div class="cart-line__quantity-group">
              <div class="quantity" :aria-label="`Quantity controls for ${item.product.name}`">
                <button
                  type="button"
                  :aria-label="`Decrease quantity for ${item.product.name}`"
                  @click="updateQuantity(item.product.id, (qty) => qty - 1)"
                >
                  –
                </button>
                <span :data-testid="`cart-qty-${item.product.id}`" aria-live="polite">
                  {{ item.quantity }}
                </span>
                <button
                  type="button"
                  :aria-label="`Increase quantity for ${item.product.name}`"
                  @click="updateQuantity(item.product.id, (qty) => qty + 1)"
                >
                  +
                </button>
              </div>
              <button
                type="button"
                class="cart-line__remove"
                :aria-label="`Remove all ${item.product.name} from cart`"
                @click="updateQuantity(item.product.id, () => 0)"
              >
                <svg
                  width="16"
                  height="16"
                  viewBox="0 0 16 16"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M2 4h12M5.333 4V2.667a1.333 1.333 0 0 1 1.334-1.334h2.666a1.333 1.333 0 0 1 1.334 1.334V4m2 0v9.333a1.333 1.333 0 0 1-1.334 1.334H4.667a1.333 1.333 0 0 1-1.334-1.334V4h9.334ZM6.667 7.333v4M9.333 7.333v4"
                    stroke="currentColor"
                    stroke-width="1.5"
                    stroke-linecap="round"
                    stroke-linejoin="round"
                  />
                </svg>
              </button>
            </div>
            <span class="cart-line__total">
              {{ currency.format(item.product.price * item.quantity) }}
            </span>
          </div>
        </li>
      </ul>
      <p v-else class="cart-panel__empty">Your basket is empty – add your favorite finds.</p>
      <div class="cart-panel__summary">
        <div class="cart-panel__summary-row">
          <span>Subtotal</span>
          <span>{{ currency.format(subtotal) }}</span>
        </div>
        <div class="cart-panel__summary-row">
          <span>Shipping</span>
          <span>{{ shipping === 0 ? 'Complimentary' : currency.format(shipping) }}</span>
        </div>
        <div class="cart-panel__summary-row cart-panel__summary-row--total">
          <span>Total</span>
          <span>{{ currency.format(total) }}</span>
        </div>
        <router-link
          to="/checkout"
          class="btn btn--primary btn--full"
          style="text-align: center; display: block; text-decoration: none"
          @click="toggleCart"
        >
          Proceed to checkout
        </router-link>
      </div>
    </section>

    <slot />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAuth } from '../composables/useAuth'
import type { Product } from '../data/products'

const currency = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
})

type CartLineItem = {
  product: Product
  quantity: number
}

interface Props {
  cartItems: CartLineItem[]
  cartCount: number
  subtotal: number
  shipping: number
  total: number
  freeShippingMessage: string
  isCartOpen: boolean
}

interface Emits {
  (e: 'toggle-cart'): void
  (e: 'update-quantity', productId: string, updater: (current: number) => number): void
}

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const { isAuthenticated, user, logout } = useAuth()
const router = useRouter()

const toggleCart = () => {
  emit('toggle-cart')
}

const updateQuantity = (productId: string, updater: (current: number) => number) => {
  emit('update-quantity', productId, updater)
}
</script>

// src/components/layout/Layout.tsx
import { Link } from 'react-router-dom'
import { useAuth } from '../../contexts/AuthContext'
import { CartLine } from '../cart/CartLine'
import { currency } from '../../utils/constants'
import type { LayoutProps } from '../../types'

export function Layout({
  children,
  cartItems,
  cartCount,
  subtotal,
  shipping,
  total,
  freeShippingMessage,
  isCartOpen,
  toggleCart,
  updateQuantity,
}: LayoutProps) {
  const { isAuthenticated, user, logout } = useAuth()

  return (
    <div className="max-w-[1200px] mx-auto px-5 lg:px-12 py-12 pb-16 flex flex-col gap-12">
      <div className="flex justify-between items-center bg-white rounded-3xl px-8 py-6 border border-slate-200">
        <div>
          <p className="text-xs tracking-widest uppercase text-slate-400">Your bag</p>
          <p className="m-0">
            {cartCount ? `${cartCount} item${cartCount > 1 ? 's' : ''}` : 'No items yet'}
          </p>
        </div>
        <div className="flex items-center gap-4">
          {isAuthenticated ? (
            <>
              <Link to="/account/orders" className="text-inherit no-underline text-sm mr-2">
                {user?.email}
              </Link>
              <button
                type="button"
                className="rounded-full px-4 py-2 text-sm font-semibold cursor-pointer transition-all bg-transparent border border-slate-200 text-slate-900 hover:-translate-y-0.5"
                onClick={logout}
              >
                Logout
              </button>
            </>
          ) : (
            <Link
              to="/login"
              className="text-inherit no-underline text-sm mr-2"
              onClick={() => {
                if (isCartOpen) {
                  toggleCart()
                }
              }}
            >
              Login
            </Link>
          )}
          <button
            type="button"
            className="inline-flex items-center gap-2.5 bg-slate-900 text-white border-none rounded-full px-5 py-3 font-semibold cursor-pointer"
            onClick={toggleCart}
            data-testid="cart-toggle"
          >
            Bag
            <span
              className="inline-flex justify-center items-center w-8 h-8 rounded-full bg-white/15"
              data-testid="cart-count"
              aria-live="polite"
            >
              {cartCount}
            </span>
          </button>
        </div>
      </div>

      {isCartOpen && (
        <section
          className="bg-white rounded-3xl border border-slate-200 p-8 lg:p-12 grid gap-6 shadow-xl shadow-slate-900/10"
          aria-live="polite"
        >
          <header className="flex justify-between items-center">
            <div>
              <p className="text-xs tracking-widest uppercase text-slate-400">Shopping bag</p>
              <h2 className="m-0">Ready to ship</h2>
            </div>
            <button
              type="button"
              className="rounded-full px-4 py-2 text-sm font-semibold cursor-pointer transition-all bg-transparent border border-slate-200 text-slate-900 hover:-translate-y-0.5"
              onClick={toggleCart}
            >
              Hide
            </button>
          </header>
          <p className="text-slate-600 m-0">{freeShippingMessage}</p>
          {cartItems.length === 0 ? (
            <p className="p-6 rounded-3xl bg-slate-50 text-center m-0">
              Your basket is empty – add your favorite finds.
            </p>
          ) : (
            <ul className="list-none m-0 p-0 flex flex-col gap-4">
              {cartItems.map((item) => (
                <CartLine
                  key={item.product.id}
                  item={item}
                  onIncrement={() => updateQuantity(item.product.id, (qty) => qty + 1)}
                  onDecrement={() => updateQuantity(item.product.id, (qty) => qty - 1)}
                  onRemove={() => updateQuantity(item.product.id, () => 0)}
                />
              ))}
            </ul>
          )}
          <div className="border-t border-slate-200 pt-4 flex flex-col gap-3">
            <div className="flex justify-between text-slate-600">
              <span>Subtotal</span>
              <span>{currency.format(subtotal)}</span>
            </div>
            <div className="flex justify-between text-slate-600">
              <span>Shipping</span>
              <span>{shipping === 0 ? 'Complimentary' : currency.format(shipping)}</span>
            </div>
            <div className="flex justify-between text-xl text-slate-900 font-semibold pt-3 border-t border-slate-200">
              <span>Total</span>
              <span>{currency.format(total)}</span>
            </div>
            <Link
              to="/checkout"
              className="rounded-full px-6 py-3.5 text-sm font-semibold cursor-pointer transition-all bg-orange-500 text-white shadow-lg shadow-orange-500/25 hover:-translate-y-0.5 text-center block no-underline"
              onClick={toggleCart}
            >
              Proceed to checkout
            </Link>
          </div>
        </section>
      )}

      {children}
    </div>
  )
}
