// src/ProductsPage.tsx
import { useEffect } from 'react'
import { useLocation } from 'react-router-dom'
import { useQuery } from '@apollo/client/react'
import ProductCard from './ProductCard'
import { GET_PRODUCTS } from './graphql/queries'
import type { Product } from './data/products'
import { LoadingState } from './components/LoadingState'
import { ErrorMessage } from './components/ErrorMessage'
import { PageContainer } from './components/PageContainer'

type ProductsPageProps = {
  addToCart: (productId: string) => void
  isHighlighted: (productId: string) => boolean
}

type ProductsQueryResult = {
  products: Product[]
}

export default function ProductsPage({ addToCart, isHighlighted }: ProductsPageProps) {
  const location = useLocation()
  const { loading, error, data } = useQuery<ProductsQueryResult>(GET_PRODUCTS)

  // Scroll to top when products page loads or location changes
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [location.pathname])

  if (loading) return <LoadingState message="Loading products..." />
  if (error) return <ErrorMessage message={`Error loading products: ${error.message}`} />

  const products = data?.products || []

  return (
    <PageContainer backLink={{ to: '/', label: '← Back to home' }} innerClassName="py-8">
      <section className="flex flex-col gap-10">
        <div className="max-w-[520px]">
          <p className="text-xs tracking-widest uppercase text-slate-400">Featured pieces</p>
          <h2 className="m-0">Crafted to layer beautifully</h2>
          <p className="m-0">
            Mix tactile fabrics, natural woods, and sculptural silhouettes for your signature look.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">
          {products.map((product: Product) => (
            <ProductCard
              key={product.id}
              product={product}
              onAdd={() => addToCart(product.id)}
              isHighlighted={isHighlighted(product.id)}
            />
          ))}
        </div>
      </section>
    </PageContainer>
  )
}

// src/views/ProductsPage.vue
<template>
  <div class="products-page">
    <router-link to="/" class="product-page__back"> ← Back to home </router-link>
    <section class="product-grid">
      <div class="section-heading">
        <p class="eyebrow">Featured pieces</p>
        <h2>Crafted to layer beautifully</h2>
        <p>
          Mix tactile fabrics, natural woods, and sculptural silhouettes for your signature look.
        </p>
      </div>
      <div v-if="loading" class="products-page">Loading products...</div>
      <div v-else-if="error" class="products-page">Error loading products: {{ error.message }}</div>
      <div v-else class="product-grid__items">
        <ProductCard
          v-for="product in products"
          :key="product.id"
          :product="product"
          :is-highlighted="isHighlighted(product.id)"
          @add="addToCart(product.id)"
        />
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { computed, inject, onMounted, watch } from 'vue'
import { useRoute } from 'vue-router'
import { useQuery } from '@vue/apollo-composable'
import ProductCard from '../components/ProductCard.vue'
import { GET_PRODUCTS } from '../graphql/queries'
import type { Product } from '../data/products'

const route = useRoute()

// Scroll to top when products page loads or location changes
onMounted(() => {
  window.scrollTo({ top: 0, behavior: 'smooth' })
})

watch(
  () => route.path,
  () => {
    window.scrollTo({ top: 0, behavior: 'smooth' })
  },
)

const { loading, error, result } = useQuery(GET_PRODUCTS)
const products = computed(() => (result.value?.products as Product[]) || [])

const addToCart = inject<(productId: string) => void>('addToCart', () => {})
const isHighlighted = inject<(productId: string) => boolean>('isHighlighted', () => false)
</script>

<style scoped>
@import '../App.css';
</style>
