// src/views/CheckoutPage.vue
<template>
  <div class="shop">
    <div class="checkout-page">
      <div v-if="cartItems.length === 0" class="checkout-page__empty">
        <h1>Your cart is empty</h1>
        <p>Add items to your cart before proceeding to checkout.</p>
        <button type="button" class="btn btn--primary" @click="router.push('/products')">
          Continue Shopping
        </button>
      </div>
      <template v-else>
        <router-link to="/products" class="product-page__back"> ← Back to products </router-link>

        <div class="checkout-page__content">
          <div class="checkout-page__form-section">
            <h1 class="checkout-page__title">Checkout</h1>

            <form class="checkout-form" @submit.prevent="handleSubmit">
              <section class="checkout-form__section">
                <h2 class="checkout-form__section-title">Shipping Address</h2>
                <div class="checkout-form__row">
                  <div class="checkout-form__group">
                    <label for="firstName" class="checkout-form__label"> First Name </label>
                    <input
                      id="firstName"
                      v-model="formData.firstName"
                      name="firstName"
                      type="text"
                      class="checkout-form__input"
                      required
                    />
                  </div>

                  <div class="checkout-form__group">
                    <label for="lastName" class="checkout-form__label"> Last Name </label>
                    <input
                      id="lastName"
                      v-model="formData.lastName"
                      name="lastName"
                      type="text"
                      class="checkout-form__input"
                      required
                    />
                  </div>
                </div>

                <div class="checkout-form__group">
                  <label for="address" class="checkout-form__label"> Street Address </label>
                  <input
                    id="address"
                    v-model="formData.address"
                    name="address"
                    type="text"
                    class="checkout-form__input"
                    required
                  />
                </div>

                <div class="checkout-form__row">
                  <div class="checkout-form__group">
                    <label for="city" class="checkout-form__label"> City </label>
                    <input
                      id="city"
                      v-model="formData.city"
                      name="city"
                      type="text"
                      class="checkout-form__input"
                      required
                    />
                  </div>

                  <div class="checkout-form__group">
                    <label for="state" class="checkout-form__label"> State </label>
                    <input
                      id="state"
                      v-model="formData.state"
                      name="state"
                      type="text"
                      class="checkout-form__input"
                      required
                    />
                  </div>

                  <div class="checkout-form__group">
                    <label for="zipCode" class="checkout-form__label"> ZIP Code </label>
                    <input
                      id="zipCode"
                      v-model="formData.zipCode"
                      name="zipCode"
                      type="text"
                      class="checkout-form__input"
                      required
                    />
                  </div>
                </div>

                <div class="checkout-form__group">
                  <label for="country" class="checkout-form__label"> Country </label>
                  <input
                    id="country"
                    v-model="formData.country"
                    name="country"
                    type="text"
                    class="checkout-form__input"
                    required
                  />
                </div>
              </section>

              <section class="checkout-form__section">
                <h2 class="checkout-form__section-title">Payment Method</h2>
                <div class="checkout-form__group">
                  <label for="paymentMethod" class="checkout-form__label"> Payment Method </label>
                  <select
                    id="paymentMethod"
                    v-model="formData.paymentMethod"
                    name="paymentMethod"
                    class="checkout-form__input"
                    required
                  >
                    <option value="CREDIT_CARD">Credit Card</option>
                    <option value="DEBIT_CARD">Debit Card</option>
                    <option value="PAYPAL">PayPal</option>
                    <option value="BANK_TRANSFER">Bank Transfer</option>
                  </select>
                </div>
              </section>

              <div v-if="error" class="checkout-form__error">
                <p>Error processing checkout: {{ error.message }}</p>
              </div>

              <button
                type="submit"
                class="btn btn--primary btn--full checkout-form__submit"
                :disabled="loading"
              >
                {{ loading ? 'Processing...' : 'Complete Order' }}
              </button>
            </form>
          </div>

          <div class="checkout-page__summary">
            <h2 class="checkout-page__summary-title">Order Summary</h2>
            <div class="checkout-page__items">
              <div v-for="item in cartItems" :key="item.product.id" class="checkout-page__item">
                <div class="checkout-page__item-info">
                  <h3>{{ item.product.name }}</h3>
                  <p>Quantity: {{ item.quantity }}</p>
                </div>
                <div class="checkout-page__item-price">
                  {{ currency.format(item.product.price * item.quantity) }}
                </div>
              </div>
            </div>
            <div class="checkout-page__totals">
              <div class="checkout-page__total-row">
                <span>Subtotal</span>
                <span>{{ currency.format(subtotal) }}</span>
              </div>
              <div class="checkout-page__total-row">
                <span>Shipping</span>
                <span>{{ shipping === 0 ? 'Complimentary' : currency.format(shipping) }}</span>
              </div>
              <div class="checkout-page__total-row checkout-page__total-row--final">
                <span>Total</span>
                <span>{{ currency.format(total) }}</span>
              </div>
            </div>
          </div>
        </div>
      </template>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, inject, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useMutation } from '@vue/apollo-composable'
import { useAuth } from '../composables/useAuth'
import { CREATE_CHECKOUT } from '../graphql/queries'
import type { Product } from '../data/products'

const currency = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
})

type CartLineItem = {
  product: Product
  quantity: number
}

const router = useRouter()
const { user } = useAuth()

const cartItems = inject<ReturnType<typeof computed<CartLineItem[]>>>('cartItems', computed(() => []))
const subtotal = inject<ReturnType<typeof computed<number>>>('subtotal', computed(() => 0))
const shipping = inject<ReturnType<typeof computed<number>>>('shipping', computed(() => 0))
const total = inject<ReturnType<typeof computed<number>>>('total', computed(() => 0))

const { mutate: createCheckout, loading, error } = useMutation(CREATE_CHECKOUT, {
  refetchQueries: [],
})

const formData = ref({
  firstName: '',
  lastName: '',
  address: '',
  city: '',
  state: '',
  zipCode: '',
  country: 'United States',
  paymentMethod: 'CREDIT_CARD',
})

  const handleSubmit = async () => {
  const items = cartItems.value
  if (items.length === 0) {
    alert('Your cart is empty')
    return
  }

  // Calculate tax (assuming 8% tax rate)
  const taxRate = 0.08
  const calculatedTax = subtotal * taxRate
  const calculatedTotal = subtotal + shipping + calculatedTax

  const createCheckoutInput = {
    items: items.map((item) => ({
      productId: item.product.id,
      name: item.product.name,
      quantity: item.quantity,
      price: item.product.price,
    })),
    shippingAddress: {
      firstName: formData.value.firstName,
      lastName: formData.value.lastName,
      address: formData.value.address,
      city: formData.value.city,
      state: formData.value.state,
      zipCode: formData.value.zipCode,
      country: formData.value.country,
    },
    paymentMethod: formData.value.paymentMethod,
    subtotal: subtotal.value,
    shipping: shipping.value,
    tax: calculatedTax,
    total: calculatedTotal,
    userId: user.value?.id,
  }

  try {
    const result = await createCheckout({ createCheckoutInput })
    if (result?.data?.createCheckout) {
      router.push(`/checkout/${result.data.createCheckout.id}/success`)
    }
  } catch (err) {
    console.error('Checkout error:', err)
  }
}
</script>

<style scoped>
@import '../App.css';
</style>

// src/CheckoutPage.tsx
import { useState } from 'react'
import type { FormEvent } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { useMutation } from '@apollo/client/react'
import './App.css'
import { CREATE_CHECKOUT } from './graphql/queries'
import type { Product } from './data/products'

const currency = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
})

type CartLineItem = {
  product: Product
  quantity: number
}

type CheckoutPageProps = {
  cartItems: CartLineItem[]
  subtotal: number
  shipping: number
  total: number
}

type CreateCheckoutInput = {
  items: Array<{
    productId: string
    name: string
    quantity: number
    price: number
  }>
  shippingAddress: {
    firstName: string
    lastName: string
    address: string
    city: string
    state: string
    zipCode: string
    country: string
  }
  paymentMethod: string
  subtotal: number
  shipping: number
  tax: number
  total: number
}

type CreateCheckoutMutationResult = {
  createCheckout: {
    id: string
    status: string
    total: number
  }
}

export default function CheckoutPage({ cartItems, subtotal, shipping, total }: CheckoutPageProps) {
  const navigate = useNavigate()
  const [createCheckout, { loading, error }] =
    useMutation<CreateCheckoutMutationResult>(CREATE_CHECKOUT)
  const [formData, setFormData] = useState({
    firstName: '',
    lastName: '',
    address: '',
    city: '',
    state: '',
    zipCode: '',
    country: 'United States',
    paymentMethod: 'CREDIT_CARD',
  })

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault()

    if (cartItems.length === 0) {
      alert('Your cart is empty')
      return
    }

    // Calculate tax (assuming 8% tax rate)
    const taxRate = 0.08
    const calculatedTax = subtotal * taxRate
    const calculatedTotal = subtotal + shipping + calculatedTax

    const createCheckoutInput: CreateCheckoutInput = {
      items: cartItems.map((item) => ({
        productId: item.product.id,
        name: item.product.name,
        quantity: item.quantity,
        price: item.product.price,
      })),
      shippingAddress: {
        firstName: formData.firstName,
        lastName: formData.lastName,
        address: formData.address,
        city: formData.city,
        state: formData.state,
        zipCode: formData.zipCode,
        country: formData.country,
      },
      paymentMethod: formData.paymentMethod,
      subtotal,
      shipping,
      tax: calculatedTax,
      total: calculatedTotal,
    }

    try {
      const { data } = await createCheckout({
        variables: { createCheckoutInput },
      })

      if (data?.createCheckout) {
        // Navigate to checkout success page or show confirmation
        navigate(`/checkout/${data.createCheckout.id}/success`)
      }
    } catch (err) {
      console.error('Checkout error:', err)
    }
  }

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    })
  }

  if (cartItems.length === 0) {
    return (
      <div className="shop">
        <div className="checkout-page">
          <div className="checkout-page__empty">
            <h1>Your cart is empty</h1>
            <p>Add items to your cart before proceeding to checkout.</p>
            <button
              type="button"
              className="btn btn--primary"
              onClick={() => navigate('/products')}
            >
              Continue Shopping
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="shop">
      <div className="checkout-page">
        <Link to="/products" className="product-page__back">
          ← Back to products
        </Link>

        <div className="checkout-page__content">
          <div className="checkout-page__form-section">
            <h1 className="checkout-page__title">Checkout</h1>

            <form className="checkout-form" onSubmit={handleSubmit}>
              <section className="checkout-form__section">
                <h2 className="checkout-form__section-title">Shipping Address</h2>
                <div className="checkout-form__row">
                  <div className="checkout-form__group">
                    <label htmlFor="firstName" className="checkout-form__label">
                      First Name
                    </label>
                    <input
                      id="firstName"
                      name="firstName"
                      type="text"
                      className="checkout-form__input"
                      value={formData.firstName}
                      onChange={handleChange}
                      required
                    />
                  </div>

                  <div className="checkout-form__group">
                    <label htmlFor="lastName" className="checkout-form__label">
                      Last Name
                    </label>
                    <input
                      id="lastName"
                      name="lastName"
                      type="text"
                      className="checkout-form__input"
                      value={formData.lastName}
                      onChange={handleChange}
                      required
                    />
                  </div>
                </div>

                <div className="checkout-form__group">
                  <label htmlFor="address" className="checkout-form__label">
                    Street Address
                  </label>
                  <input
                    id="address"
                    name="address"
                    type="text"
                    className="checkout-form__input"
                    value={formData.address}
                    onChange={handleChange}
                    required
                  />
                </div>

                <div className="checkout-form__row">
                  <div className="checkout-form__group">
                    <label htmlFor="city" className="checkout-form__label">
                      City
                    </label>
                    <input
                      id="city"
                      name="city"
                      type="text"
                      className="checkout-form__input"
                      value={formData.city}
                      onChange={handleChange}
                      required
                    />
                  </div>

                  <div className="checkout-form__group">
                    <label htmlFor="state" className="checkout-form__label">
                      State
                    </label>
                    <input
                      id="state"
                      name="state"
                      type="text"
                      className="checkout-form__input"
                      value={formData.state}
                      onChange={handleChange}
                      required
                    />
                  </div>

                  <div className="checkout-form__group">
                    <label htmlFor="zipCode" className="checkout-form__label">
                      ZIP Code
                    </label>
                    <input
                      id="zipCode"
                      name="zipCode"
                      type="text"
                      className="checkout-form__input"
                      value={formData.zipCode}
                      onChange={handleChange}
                      required
                    />
                  </div>
                </div>

                <div className="checkout-form__group">
                  <label htmlFor="country" className="checkout-form__label">
                    Country
                  </label>
                  <input
                    id="country"
                    name="country"
                    type="text"
                    className="checkout-form__input"
                    value={formData.country}
                    onChange={handleChange}
                    required
                  />
                </div>
              </section>

              <section className="checkout-form__section">
                <h2 className="checkout-form__section-title">Payment Method</h2>
                <div className="checkout-form__group">
                  <label htmlFor="paymentMethod" className="checkout-form__label">
                    Payment Method
                  </label>
                  <select
                    id="paymentMethod"
                    name="paymentMethod"
                    className="checkout-form__input"
                    value={formData.paymentMethod}
                    onChange={handleChange}
                    required
                  >
                    <option value="CREDIT_CARD">Credit Card</option>
                    <option value="DEBIT_CARD">Debit Card</option>
                    <option value="PAYPAL">PayPal</option>
                    <option value="BANK_TRANSFER">Bank Transfer</option>
                  </select>
                </div>
              </section>

              {error && (
                <div className="checkout-form__error">
                  <p>Error processing checkout: {error.message}</p>
                </div>
              )}

              <button
                type="submit"
                className="btn btn--primary btn--full checkout-form__submit"
                disabled={loading}
              >
                {loading ? 'Processing...' : 'Complete Order'}
              </button>
            </form>
          </div>

          <div className="checkout-page__summary">
            <h2 className="checkout-page__summary-title">Order Summary</h2>
            <div className="checkout-page__items">
              {cartItems.map((item) => (
                <div key={item.product.id} className="checkout-page__item">
                  <div className="checkout-page__item-info">
                    <h3>{item.product.name}</h3>
                    <p>Quantity: {item.quantity}</p>
                  </div>
                  <div className="checkout-page__item-price">
                    {currency.format(item.product.price * item.quantity)}
                  </div>
                </div>
              ))}
            </div>
            <div className="checkout-page__totals">
              <div className="checkout-page__total-row">
                <span>Subtotal</span>
                <span>{currency.format(subtotal)}</span>
              </div>
              <div className="checkout-page__total-row">
                <span>Shipping</span>
                <span>{shipping === 0 ? 'Complimentary' : currency.format(shipping)}</span>
              </div>
              <div className="checkout-page__total-row checkout-page__total-row--final">
                <span>Total</span>
                <span>{currency.format(total)}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
